# Generated by Django 6.0.4 on 2026-04-30 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_subscription_options_alter_subscription_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Invoice amount in EGP', max_digits=10)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('vodafone_cash', 'Vodafone Cash'), ('instapay', 'Instapay'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('waiting_approval', 'Waiting for Approval'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction ID or reference number from payment provider', max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer')),
                ('subscription', models.ForeignKey(blank=True, help_text='Optional: Link to subscription if this invoice is for a subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'status'], name='payments_in_custome_fd2c3d_idx'), models.Index(fields=['status', 'created_at'], name='payments_in_status_a745e9_idx'), models.Index(fields=['payment_type', 'status'], name='payments_in_payment_dcf87e_idx')],
            },
        ),
    ]
