# Generated by Django 6.0.4 on 2026-05-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='subscription',
            field=models.CharField(choices=[('monthly', 'Monthly (unlimited)'), ('session_pack', 'Session pack'), ('single visit', 'Single visit')], default='monthly', max_length=20),
        ),
    ]
