# Generated by Django 6.0.4 on 2026-05-03 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_subscription_invoice_number'),
        ('payments', '0002_alter_invoice_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subscription',
            field=models.OneToOneField(blank=True, help_text='The subscription this invoice was generated for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='customers.subscription'),
        ),
    ]
