# Generated by Django 6.0.4 on 2026-05-03 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_subscription_invoice_number'),
        ('payments', '0003_invoice_invoice_number_alter_invoice_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='subscription',
            field=models.OneToOneField(blank=True, choices=[('monthly', 'Monthly (unlimited)'), ('session_pack', 'Session pack'), ('single visit', 'Single visit')], help_text='The subscription this invoice was generated for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='customers.subscription'),
        ),
    ]
