# Generated by Django 6.0.4 on 2026-04-29 19:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='Barcode must be exactly 4 digits.', regex='^\\d{4}$')])),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=15, unique=True)),
                ('id_number', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='ID number must be exactly 14 digits.', regex='^\\d{14}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_limit', models.PositiveSmallIntegerField(blank=True, choices=[(8, '8 sessions'), (12, '12 sessions'), (16, '16 sessions')], null=True)),
                ('sessions_used', models.PositiveSmallIntegerField(default=0)),
                ('kind', models.CharField(choices=[('monthly', 'Monthly (unlimited)'), ('session_pack', 'Session pack'), ('single visit', 'One single visit')], default='monthly', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='customers.customer')),
            ],
        ),
    ]
