# Generated by Django 6.0.4 on 2026-04-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='kind',
            field=models.CharField(choices=[('monthly', 'Monthly (unlimited)'), ('session_pack', 'Session pack')], default='monthly', max_length=20),
        ),
    ]
