# Generated by Django 6.0.4 on 2026-04-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_subscription_options_alter_subscription_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='kind',
            field=models.CharField(choices=[('monthly', 'Monthly (unlimited)'), ('session_pack', 'Session pack'), ('single visit', 'Single visit')], default='monthly', max_length=20),
        ),
    ]
