# Generated by Django 6.0.4 on 2026-05-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_subscription_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='invoice_number',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True),
        ),
    ]
