# Generated by Django 6.0.4 on 2026-05-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_subscription_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
