# Generated by Django 6.0.4 on 2026-04-30 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='subscription',
        ),
    ]
