# Generated by Django 6.0.4 on 2026-05-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0003_remove_checkin_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='customer_barcode',
            field=models.CharField(db_index=True, max_length=4, null=True),
        ),
    ]
