# Generated by Django 6.0.4 on 2026-05-08 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0004_checkin_customer_barcode'),
        ('customers', '0006_customer_customer_full_name_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['customer', '-created_at'], name='checkin_customer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['created_at'], name='checkin_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['customer_barcode', '-created_at'], name='checkin_barcode_date_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['visit_type', 'created_at'], name='checkin_visit_type_date_idx'),
        ),
    ]
