# Generated by Django 6.0.5 on 2026-06-09 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0005_checkin_checkin_customer_date_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='checkin',
            name='checkin_barcode_date_idx',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='customer_barcode',
        ),
    ]
