# Generated by Django 6.0.5 on 2026-06-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0006_remove_checkin_checkin_barcode_date_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='visit_type',
            field=models.CharField(choices=[('walk_in', 'Walk-in'), ('free_trial', 'Free trial'), ('subscription', 'Subscription')], db_index=True, default='subscription', max_length=20),
        ),
    ]
