# Generated by Django 6.0.5 on 2026-06-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0007_alter_checkin_visit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='visit_type',
            field=models.CharField(choices=[('walk_in', 'Walk-in'), ('free_trial', 'Free trial'), ('subscription', 'Subscription')], db_index=True, max_length=20),
        ),
    ]
